### ISSUE TITLE
Querystrings stops the url to lowercase

### ISSUE THREAD

**Issue by aharonrossano** [joshbuchea/wp-force-lowercase-urls#1]
When querystrings are appended it doesn't lowercase the URL.
So I tested:
Correct: https://example.com/Contact/ > https://example.com/contact/

Incorrect: https://example.com/Contact/?Test > https://example.com/Contact/?Test
I would've expected: https://example.com/contact/?Test

**Comment by joshbuchea** [comment]
You are absolutely correct. I will push up a fix tomorrow. Thanks!

**Comment by joshbuchea** [comment]
Ha it took me a bit longer than a day :grin: but I just pushed up v2 which resolves this issue. Thanks!
