### ISSUE TITLE
Update WordPress.org plugin page

### ISSUE THREAD

**Issue by cawel** [joshbuchea/wp-force-lowercase-urls#2]
Your [WordPress.org plugin page](https://wordpress.org/plugins/wp-force-lowercase-urls/) says: 

> Last Updated: 1 year ago
> Compatible up to: 4.7.10

When trying to install the plugin, I see this:

```
Warning: This plugin has not been tested with your current version of WordPress.
```

I currently use the latest WordPress version (4.9.6). Nevertheless, I installed the plugin and it works fine. 

Maybe you could make some tests to confirm and thereafter update the info on the WordPress.org plugin page? That would give more credibility to that nice plugin.

**Comment by joshbuchea** [comment]
Thanks for pointing this out @cawel 🙌 I'll update it.

**Comment by joshbuchea** [comment]
✅ Updated
