### ISSUE TITLE
Test Plugin With WordPress 5.0

### ISSUE THREAD

**Issue by joshbuchea** [joshbuchea/wp-force-lowercase-urls#4]
WordPress 5.0 is scheduled to be released on **November 19**. The plugin needs to be tested against the new version to verify compatibility.

**Comment by keoy7am** [comment]
I tested it on WordPress 5.0,It's work!

**Comment by joshbuchea** [comment]
@keoy7am apologies for my late response. Thank you for testing this! 🙏 I bumped the **Tested up to** version in the README and **just** pushed the update, so it should be reflected in the plugin directory soon! Thanks again!
